[package]
name = "graphapi"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
db = { version = "0.1.0", path = "../db" }
reqwest = { version="0.12.24", features=["blocking", "multipart"] }
serde = { version="1.0.228", features=["derive"] }
serde_json = "1.0.145"
toml = "0.9.8"
